# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "timestop"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Dungeon Time Stop"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description = """
Adds the ability to stop the time when in dungeons and temples via the configuration.
Temples covers the four temples and the boss rooms.
All covers the temples plus any mini-dungeon like Pirate's Fortress, the Well, Ikana Castle etc.
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "ez mode"

# Authors of this mod.
authors = ["calumcl"]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    # Example dependency:
    #    "modname:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
    # Example native library:
    #    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "timestop"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [
    "Zelda64RecompSyms/mm.us.rev1.datasyms.toml",
    "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml",
]

# Additional files to include in the mod.
additional_files = []

[[manifest.config_options]]
id = "timestop_option"
name = "Time Stop Locations"
description = "Where to stop time"
type = "Enum"
options = ["Off", "Temples", "All"]
default = "Temples"
